name: workspace_blank
packages:
  - packages/*

scripts:
  build:
    description: "Build all packages in the repo"
    run: |
      melos run build

  publish:
    description: "Publish all packages in the repo"
    run: |
      melos publish

  update-dependencies:
    description: "Update Dart dependencies for all packages in the repo"
    run: |
      melos bootstrap
