name: workspace_blank
description: A new Dart package for demonstrating functionality.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  dartdoc: ^0.41.0
  melos: ^1.0.0
