name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '2.12.0'

    - name: Install Melos
      run: dart pub global activate melos

    - name: Bootstrap dependencies
      run: melos bootstrap

    - name: Run tests
      run: melos run test
